[package]
name = "md"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.27.0"
wgpu = "0.14.0"
futures = "0.3.21"
pollster = "0.3.0"
glyph_brush = "0.7.12"
glyph_brush_layout = "0.2.3"
ab_glyph = "0.2.21"
